### ISSUE TITLE
无法获取

### ISSUE THREAD

**Issue by imyyq-star** [CaiJingLong/flutter_resource_generator#1]
flutter_resource_generator any which doesn't exist (could not find package flutter_resource_generator at https://pub.flutter-io.cn), version solving failed.

**Comment by CaiJingLong** [comment]
https://pub.flutter-io.cn/packages/flutter_asset_generator

I don't know your means.

**Comment by CaiJingLong** [comment]
This is the code I wrote shortly after using flutter.
Later I will rewrite this in the form of [pub global](https://www.dartlang.org/tools/pub/cmd/pub-global) instead of build_runner.

**Comment by CaiJingLong** [comment]
国内的镜像有时会出现问题, 请使用官方镜像源下载.
Domestic mirrors sometimes have problems, please use the official mirror source to download.

mac or linux:
unset FLUTTER_STORAGE_BASE_URL
unset PUB_HOSTED_URL

windows:
System=>environment variables

**Comment by CaiJingLong** [comment]
Update version to 0.4.0.
Try to use it with [pub global](https://www.dartlang.org/tools/pub/cmd/pub-global).
