### ISSUE TITLE
fgen Failed to precompile 

### ISSUE THREAD

**Issue by zmm2tysu** [CaiJingLong/flutter_resource_generator#18]
项目根目录执行fgen后报下面这个错误

![image](https://user-images.githubusercontent.com/20849786/127423238-d46c9b01-09c3-4949-9e3a-813524aa7aca.png)

Flutter Doctor
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)
```

**Comment by AlexV525** [comment]
使用 1.0.0-nullsafety.0

**Comment by zmm2tysu** [comment]
![image](https://user-images.githubusercontent.com/20849786/127423695-d49f4906-8eb1-43e3-bcfe-3257c599a850.png)
怎么更新到1.0啊

**Comment by AlexV525** [comment]
dart pub global activate flutter_asset_generator 1.0.0-nullsafety.0
